Themes_15_18/StateWeb/StateWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

if settings.DEBUG:
    if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Themes_15_18/StateWeb/base/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [   

    # Маршруты для работы с людьми 
    path('', views.human_list, name='human_list'),
    path('add/', views.add_human, name='add_human'),
    path('human/<int:pk>/', views.human_detail, name='human_detail'),
    path('human/<int:pk>/delete/', views.delete_human, name='delete_human'),
    path('human/<int:pk>/edit/', views.edit_human, name='edit_human'),

    # Маршруты для работы с городами
    path('city_list/', views.city_list, name='city_list'),
    path('add_city/', views.add_city, name='add_city'),
    path('city/<int:pk>/', views.city_detail, name='city_detail'),
    path('city/<int:pk>/delete/', views.delete_city, name='delete_city'),
    path('city/<int:pk>/edit/', views.edit_city, name='edit_city'),

    # Маршруты для работы со странами
    path('country_list/', views.country_list, name='country_list'),
    path('add_country/', views.add_country, name='add_country'),
    path('country/<int:pk>/', views.country_detail, name='country_detail'),
    path('country/<int:pk>/delete/', views.delete_country, name='delete_country'),
    path('country/<int:pk>/edit/', views.edit_country, name='edit_country'),
]

Themes_15_18/StateWeb/base/models.py
from django.db import models

# Create your models here.

from django.db import models

class City(models.Model):
    name = models.CharField(max_length=100)
    population = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=100)
    area = models.PositiveIntegerField()
    population = models.PositiveIntegerField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Human(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_birth = models.DateField()
    place_residence = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.surname}"

Themes_15_18/StateWeb/base/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Human
from .human_form import HumanForm
from .models import City
from .city_form import CityForm
from .models import Country
from .country_form import CountryForm

# Create your views here.


# Маршруты для работы с людьми 
def human_list(request):
    humans = Human.objects.all()
    context = {'title': 'Главная страница сайта', 'humans': humans}
    return render(request, 'human_list.html', context)

def add_human(request):
    cities = City.objects.all() 
    if request.method == 'POST':
        form = HumanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('human_list')  # перенаправляем на страницу успешного добавления
    else:
        form = HumanForm()
    return render(request, 'add_human.html', {'form': form, 'cities': cities})


def human_detail(request, pk):
    human = get_object_or_404(Human, pk=pk)
    return render(request, 'human_detail.html', {'human': human})


def delete_human(request, pk):
    human = get_object_or_404(Human, pk=pk)
    human.delete()
    return redirect('human_list')


def edit_human(request, pk):
    human = get_object_or_404(Human, pk=pk)
    if request.method == 'POST':
        form = HumanForm(request.POST, instance=human)
        if form.is_valid():
            form.save()
            return redirect('human_list')
    else:
        form = HumanForm(instance=human)

    return render(request, 'edit_human.html', {'form': form})


# Маршруты для работы с городами
def city_list(request):
    cities = City.objects.all()
    context = {'title': 'Города', 'cities': cities}
    return render(request, 'city_list.html', context)

def add_city(request):    
    error = ''
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('city_list')
        else:
            error = "Форма была не верной"
    form = CityForm()
    context = {        
        'form': form,
        'error': error
    }
    return render(request, 'add_city.html', context)

def city_detail(request, pk):
    city = get_object_or_404(City, pk=pk)
    return render(request, 'city_detail.html', {'city': city})


def delete_city(request, pk):
    city = get_object_or_404(City, pk=pk)
    city.delete()
    return redirect('city_list')


def edit_city(request, pk):
    city = get_object_or_404(City, pk=pk)
    if request.method == 'POST':
        form = CityForm(request.POST, instance=city)
        if form.is_valid():
            form.save()
            return redirect('city_list')
    else:
        form = CityForm(instance=city)

    return render(request, 'edit_city.html', {'form': form})


# Маршруты для работы со странами
def country_list(request):
    countries = Country.objects.all()
    context = {'title': 'Страны', 'countries': countries}
    return render(request, 'country_list.html', context)

def add_country(request):    
    error = ''
    if request.method == 'POST':
        form = CountryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('country_list')
        else:
            error = "Форма была не верной"
    form = CountryForm()
    context = {        
        'form': form,        
        'error': error
    }
    return render(request, 'add_country.html', context)

def country_detail(request, pk):
    country = get_object_or_404(Country, pk=pk)
    return render(request, 'country_detail.html', {'country': country})


def delete_country(request, pk):
    country = get_object_or_404(Country, pk=pk)
    country.delete()
    return redirect('country_list')


def edit_country(request, pk):
    country = get_object_or_404(Country, pk=pk)
    if request.method == 'POST':
        form = CountryForm(request.POST, instance=country)
        if form.is_valid():
            form.save()
            return redirect('country_list')
    else:
        form = CountryForm(instance=country)

    return render(request, 'edit_country.html', {'form': form})

Themes_15_18/StateWeb/base/templates/add_city.html
{% extends 'base.html' %}

{% block title %}Добавление города{% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Добавление города</h1><br>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
    <span>{{ error }}</span> 
  </form>
{% endblock %}

Themes_15_18/StateWeb/base/templates/add_country.html
{% extends 'base.html' %}

{% block title %}Добавление страны{% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Добавление страны</h1><br>
  <form method="POST" class="form">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="{{ form.name.id_for_label }}">Name:</label>
      {{ form.name }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.area.id_for_label }}">Area:</label>
      {{ form.area }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.population.id_for_label }}">Population:</label>
      {{ form.population }}
    </div>
    
    <div class="form-group">
      <label for="{{ form.city.id_for_label }}">City:</label>
      {{ form.city }}
    </div>
    
    <button type="submit">Добавить</button>
    <span>{{ error }}</span> 
  </form>
  
{% endblock %}

Themes_15_18/StateWeb/base/templates/add_human.html
{% extends 'base.html' %}

{% block title %}Добавление человека{% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Добавление человека</h1><br>
  <form method="post" class="form">
    {% csrf_token %}
    <label for="id_name">Имя:</label>
    <input type="text" name="name" id="id_name" required><br><br>
    <label for="id_surname">Фамилия:</label>
    <input type="text" name="surname" id="id_surname" required><br><br>
    <label for="id_date_birth">Дата рождения:</label>
    <input type="date" name="date_birth" id="id_date_birth" required><br><br>
    <label for="id_place_residence">Место проживания:</label>
    <select name="place_residence" id="id_place_residence" required>
      {% for city in cities %}
      <option value="{{ city.id }}">{{ city.name }}</option>
      {% endfor %}
    </select><br><br>
    <button type="submit">Добавить</button>
    <span>{{ error }}</span> 
  </form>
{% endblock %}

Themes_15_18/StateWeb/base/templates/base.html
<!doctype html>
<html lang="ru">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header data-bs-theme="dark">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">My List Humans</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'human_list' %}">Главная</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'add_human' %}">Добавить людей </a>
                </li>   
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'city_list' %}">Города </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_city' %}">Добавить город </a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'country_list' %}">Страны</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_country' %}">Добавить страну </a>
                </li>                      
                <li class="nav-item">
                  <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
      </header>
    <div class="container">
        {% block content %} 
        
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Themes_15_18/StateWeb/base/templates/city_detail.html
{% extends 'base.html' %}

{% block title %}
{{ city.name}}
{% endblock %}

{% block content %}
<br>
<div class="container mt-5">
  <h1 class="text-center">{{ city.name}}</h1><br>
  <div class="alert alert-info">    
    <h2>Численность населения: {{ city.population }}</h2>
    <a href="{% url 'delete_city' city.pk %}" class="btn btn-danger">Удалить</a>  
    <a href="{% url 'edit_city' city.pk %}" class="btn btn-success">Изменить</a>  
  </div>     
</div>
{% endblock %}

Themes_15_18/StateWeb/base/templates/city_list.html
{% extends 'base.html' %}

{% block title %}Список городов{% endblock %}

{% block content %}
<br><br><br>
  <h1>Список городов</h1>
  {% if cities %}
    <table class="table">
      <thead>
        <tr>         
          <th>Наименование</th>
          <th>Численность населения</th>     
          <th>Детали</th>   
        </tr>
      </thead>
      <tbody>
        {% for city in cities %}
          <tr>           
            <td>{{ city.name }}</td>
            <td>{{ city.population }}</td>            
            <td><a href="{% url 'city_detail' city.pk %}" class="btn btn-warning">Детальнее</a></td>

          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>У нас нет записей!</p>
  {% endif %}
{% endblock %}

Themes_15_18/StateWeb/base/templates/country_detail.html
{% extends 'base.html' %}

{% block title %}
{{ country.name}}
{% endblock %}

{% block content %}
<br>
<div class="container mt-5">
  <h1 class="text-center">{{ country.name}}</h1><br>
  <div class="alert alert-info">   
    <h2>Площадь: {{ country.area }}</h2> 
    <h2>Численность населения: {{ country.population }}</h2>
    <h2>Город: {{ country.city }}</h2>
    <a href="{% url 'delete_country' country.pk %}" class="btn btn-danger">Удалить</a>  
    <a href="{% url 'edit_country' country.pk %}" class="btn btn-success">Изменить</a>  
  </div>     
</div>
{% endblock %}

Themes_15_18/StateWeb/base/templates/country_list.html
{% extends 'base.html' %}

{% block title %}Список стран{% endblock %}

{% block content %}
<br><br><br>
  <h1>Список стран</h1>
  {% if countries  %}
    <table class="table">
      <thead>
        <tr>         
          <th>Название</th>
          <th>Площадь</th>
          <th>Численность населения</th>          
          <th>Город</th>
          <th>Детали</th>
        </tr>
      </thead>
      <tbody>
        {% for country in countries %}
          <tr>           
            <td>{{ country.name }}</td>
            <td>{{ country.area }}</td>            
            <td>{{ country.population }}</td>            
            <td>{{ country.city }}</td>
            <td><a href="{% url 'country_detail' country.pk %}" class="btn btn-warning">Детальнее</a></td>

          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>У нас нет записей!</p>
  {% endif %}
{% endblock %}

Themes_15_18/StateWeb/base/templates/edit_city.html
{% extends 'base.html' %}

{% block title %}Редактирование города{% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Редактирование города</h1><br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Изменить город</button>
    <span>{{ error }}</span> 
 </form>
{% endblock %}

Themes_15_18/StateWeb/base/templates/edit_country.html
{% extends 'base.html' %}

{% block title %}Редактирование {% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Редактирование страны</h1><br>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
    <span>{{ error }}</span> 
  </form>
{% endblock %}

Themes_15_18/StateWeb/base/templates/edit_human.html
{% extends 'base.html' %}

{% block title %}Редактирование человека{% endblock %}

{% block content %}
<br><br><br>
  <h1 class="text-center">Редактирование человека</h1><br>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
    <span>{{ error }}</span> 
  </form>
{% endblock %}

Themes_15_18/StateWeb/base/templates/human_detail.html
{% extends 'base.html' %}

{% block title %}
{{ human.name }} {{ human.surname }}
{% endblock %}

{% block content %}
<br>
<div class="container mt-5">
  <h1 class="text-center">{{ human.name }} {{ human.surname }}</h1><br>
  <div class="alert alert-info">
    <h1> Дата рождения: {{ human.date_birth }}</h1>   
    <h2>Место проживания: {{ human.place_residence }}</h2>
    <a href="{% url 'delete_human' human.pk %}" class="btn btn-danger">Удалить</a>  
    <a href="{% url 'edit_human' human.pk %}" class="btn btn-success">Изменить</a>  
  </div>     
</div>
{% endblock %}

Themes_15_18/StateWeb/base/templates/human_list.html
{% extends 'base.html' %}

{% block title %}Список людей{% endblock %}

{% block content %}
<br><br><br>
  <h1>Список людей</h1>
  {% if humans  %}
    <table class="table">
      <thead>
        <tr>         
          <th>Имя</th>
          <th>Фамилия</th>
          <th>Дата рождения</th>          
          <th>Место жительства</th>
          <th>Детали</th>
        </tr>
      </thead>
      <tbody>
        {% for human in humans %}
          <tr>           
            <td>{{ human.name }}</td>
            <td>{{ human.surname }}</td>            
            <td>{{ human.date_birth }}</td>            
            <td>{{ human.place_residence }}</td>
            <td><a href="{% url 'human_detail' human.pk %}" class="btn btn-warning">Детальнее</a></td>

          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>У нас нет записей!</p>
  {% endif %}
{% endblock %}